[build]
  command = "pnpm build"
  functions = "netlify/functions"
  publish = "./"


[[plugins]]
package = "./prisma-client-plugin"
  

[dev]
  command = "pnpm start"
  targetPort = 4000
  publish = "frontend/dist"